[package]
name = "shoebill"
version = "0.1.0"
authors = ["ammkrn <ammkrn@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.5.1"
rustc-hash = "1.1.0"
